# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"main": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://corticometrics.github.io/scwlch/"

git_url = "https://github.com/corticometrics/scwlch/tree/master/"


def custom_doc_links(name): return None
